name: rosetta_fluter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.27.0+27

environment:
  sdk: ">=2.10.0 <3.0.0"
  #sdk: ">=2.12.0 <3.0.0"


# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  #flutter_chips_input: ^1.10.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  nb_utils: ^4.4.8
  flutter_slidable: ^1.1.0
  url_launcher: ^6.0.3
  cached_network_image: ^3.1.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  sleek_circular_slider : ^2.0.1
  #syncfusion_flutter_gauges: ^19.3.55
  step_progress_indicator: ^1.0.1
  http: ^0.13.3
  flutter_secure_storage: ^5.0.2
  multi_select_flutter: ^4.0.0
  modal_progress_hud: ^0.1.3
  progress_dialog: ^1.2.4
#  connectivity: ^3.0.6
  flutter_downloader: ^1.7.1
  dio: ^4.0.4
  external_path: ^1.0.1
  permission_handler: ^9.2.0
  flutter_countdown_timer: ^4.1.0
  open_file: ^3.2.1
  file_picker: ^4.3.3
  path_provider: ^2.0.9
  flutter_share: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.2
  text_scroll: ^0.0.5
  marquee: ^2.2.1












dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.5.0-dev.2
  shared_preferences: ^2.0.9
  flutter_launcher_icons: ^0.9.2




flutter_icons:
  android: "launcher_icon"
  ios: true
#  image_path: "images/rgallery.png"
  image_path: "images/ic_app_icon2.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - fonts/
    - assets/
    - images/
    - images/shophop/img/
    - assets/shophop_data/
    - images/shophop/img/products/
    - images/shophop/img/products/dress/
    - images/shophop/img/products/banners/
    - images/shophop/img/products/decor/
    - images/shophop/
    - images/ic_app_icon2.png
    - images/splash.png
    - images/downloadrosetta.png
    - images/buttonvs.png
    - images/downloadround.png
    - images/shareround.png
    - images/technicalspaces.png
    - images/viewinstudio.png
    - images/approvesearch.png
    - images/orderhistory.png
    - images/plus.png
    - images/minus.png
    - images/deleteitem.png
    - images/rosettaicon.png
    - images/infoicon.png
    - images/ic_calender.png
    - images/icviewinstudio.png
    - images/icroundeye.png
    - images/contactus.png
    - images/order.png
    - images/shophop/img/products/pvc2.jpg
    - images/check.png
    - images/uncheck.png
    - images/filter.png
    - images/circularbucket.png
    - images/home2.png
    - images/blockround.png
    - images/eyegolden.png
    - images/studio.png
    - images/uncheckwhite.png
    - images/checkwhite.png
    - images/enddate.png
    - images/searchroundicon.png
    - images/o1.png
    - images/o2.png
    - images/o3.png
    - images/o4.png
    - images/o5.png
    - images/delete.png
    - images/transporter.png
    - images/dealer.png
    - images/sideicon1.png
    - images/sideicon2.png
    - images/sideicon3.png
    - images/sideicon4.png
    - images/stock.png
    - images/room.png
    - images/room-1.png
    - images/checkgreen.gif
    - images/crossdialog.png
    - images/circularGreenCheckBox.png
    - images/autocompleted.png
    - images/cancel.png
    - images/pending.png
    - images/eyegrey.png
    - images/block_icon_red.png
    - images/uncheksvg.svg
    - images/checksvg.svg
    - images/addcartnotice.gif
    - images/blockednotice.gif
    - images/ani_gif.gif
    - images/form_preloader.gif
    - images/unlockcart.png
    - images/pendingdispatch.png
    - images/pendinginvoice.png
    - images/c2.png
    - images/c3.png
    - images/c4.png
    - images/c5.png
    - images/pdfimage.png
    - images/pdfblack.png
    - images/ic_pdf.png
    - images/rgallery.png
    - images/partiallyshippedstatus.png
    - images/shippedstatus.png
    - images/bg_background.jpg
    - images/bgadddealer.png
    - images/nextdisable.png
    - images/nextenable.png
    - images/viewdealers.png
    - images/c2_r.png
    - images/c3_r.png
    - images/c4_r.png
    - images/downloadround_r.png
    - images/form_preloader_r.gif
    - images/o2_r.png
    - images/searchroundicon_r.png
    - images/shareround_r.png
    - images/red_line.png
    - images/ic_round_color.png
    - images/ic_purchase_amount.png
    - images/ic_cart_dashboard.png
    - images/credit_used.png
    - images/credit_available.png
    - images/info.png
    - images/infdownarrow.png
    - images/bgdownarrow.png










  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:0
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
